### ISSUE TITLE
"Own gene set" query fails each time

### ISSUE THREAD

**Issue by guezugez** [bhasin-lab/SurvivalGenie#1]
Trying to test "gene sets" analysis using own list of 4 genes under "own gene list" but an error message occurs each time as "Server disconnected". The error message occurs irrespective of Program (TCGA, TARGET....) or Datasets.

**Comment by reemabaskar** [comment]
I am experiencing the same issue and would really like to run my own gene set, thanks!

**Comment by bhasin-lab** [comment]
We fixed this bug
